- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{ inventory_hostname }}"
    state: present