---
- name: Install zabbix-agent to windows servers
  hosts: windows_servers
  gather_facts: yes
  roles:
    - zabbix-windows-server
    - zabbix-host

# - name: Install zabbix-agent to redhat hosts
#   hosts: redhat
#   gather_facts: yes
#   roles:
#     - zabbix-redhat
#     - zabbix-host
