---
- name: Configure and monitor windows using zabbix agent
  hosts: windows
  gather_facts: yes
  roles:
    - zabbix-configure-windows
    - add-host-to-zabbix-server

- name: Configure and monitor redhat hosts using zabbix agent
  hosts: redhat
  gather_facts: yes
  roles:
    - zabbix-configure-redhat
    - add-host-to-zabbix-server

- name: Add SNMP devices to zabbix
  hosts: snmp
  gather_facts: no
  roles:
    - add-host-to-zabbix-server
