---
- name: Add host to zabbix server
  local_action:
    module: zabbix_host
    zabbix_server_api_url: "{{ zabbix_server_api_url }}"
    zabbix_server_user: "{{ zabbix_server_user }}"
    zabbix_server_password: "{{ zabbix_server_password }}"
    zabbix_host_name: "{{ zabbix_host_name }}"
    zabbix_host_ip: "{{ zabbix_host_ip }}"
    zabbix_host_type: "{{ zabbix_host_type }}"
    zabbix_interface_type: "{{ zabbix_interface_type }}"
    zabbix_agent_port: "{{ zabbix_agent_port }}"
    zabbix_snmp_port: "{{ zabbix_snmp_port }}"
    snmp_v2_community_string: "{{ snmp_v2_community_string }}"
    snmp_v3_security_name: "{{ snmp_v3_security_name }}"
    snmp_v3_auth_protocol: "{{ snmp_v3_auth_protocol }}"
    snmp_v3_auth_passphrase: "{{ snmp_v3_auth_passphrase }}"
    snmp_v3_priv_protocol: "{{ snmp_v3_priv_protocol }}"
    snmp_v3_priv_passphrase: "{{ snmp_v3_priv_passphrase }}"
    snmp_version: "{{ 3 if use_snmp_v3 else 2 }}"