---
- include_tasks: configure_hostname.yml
  when: configure_hostname

- include_tasks: configure_zabbix_agent.yml
  when: not install_zabbix_agent_v2

- include_tasks: configure_zabbix_agent2.yml
  when: install_zabbix_agent_v2